### ISSUE TITLE
no module named 'gencpp' erro even after install ros-noetic-gencpp

### ISSUE THREAD

**Issue by coddiw0mple** [ros/ros_comm_msgs#15]
This is the output thrown at me

```
Traceback (most recent call last):
File "/opt/ros/noetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 49, in <module>
genmsg.template_tools.generate_from_command_line_options(
File "/usr/lib/python3.10/site-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
File "/usr/lib/python3.10/site-packages/genmsg/template_tools.py", line 154, in generate_from_file
_generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
File "/usr/lib/python3.10/site-packages/genmsg/template_tools.py", line 93, in _generate_msg_from_file
_generate_from_spec(input_file,
File "/usr/lib/python3.10/site-packages/genmsg/template_tools.py", line 82, in _generate_from_spec
interpreter.file(open(template_file)) #todo try
File "/usr/lib/python3.10/site-packages/em.py", line 2359, in file
self.safe(scanner, done, locals)
File "/usr/lib/python3.10/site-packages/em.py", line 2401, in safe
self.parse(scanner, locals)
File "/usr/lib/python3.10/site-packages/em.py", line 2421, in parse
token.run(self, locals)
File "/usr/lib/python3.10/site-packages/em.py", line 1425, in run
interpreter.execute(self.code, locals)
File "/usr/lib/python3.10/site-packages/em.py", line 2596, in execute
_exec(statements, self.globals, locals)
File "<string>", line 4, in <module>
ModuleNotFoundError: No module named 'gencpp'
Exception ignored in: <function Interpreter.__del__ at 0x7f794ae88c10>
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/em.py", line 2094, in __del__
File "/usr/lib/python3.10/site-packages/em.py", line 2157, in shutdown
File "/usr/lib/python3.10/site-packages/em.py", line 2647, in finalize
File "/usr/lib/python3.10/site-packages/em.py", line 2200, in push
AttributeError: '_io.TextIOWrapper' object has no attribute 'push'
make[2]: *** [CMakeFiles/rosgraph_msgs_generate_messages_cpp.dir/build.make:77: devel/include/rosgraph_msgs/Clock.h] Error 1
make[2]: *** Deleting file 'devel/include/rosgraph_msgs/Clock.h'
make[1]: *** [CMakeFiles/Makefile2:539: CMakeFiles/rosgraph_msgs_generate_messages_cpp.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
Aborting...
-> error making: ros-noetic-rosgraph-msgs

```

I've tried installing ros-noetic-gencpp and hunted for pypi packages too but it doesn't seem to work, and the pypi packages do not exist

**Comment by Drisya-BL** [comment]
https://github.com/introlab/rtabmap_ros/issues/1081
